'''
Django settings for schoolManagement project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
'''

from pathlib import Path
from django.contrib.messages import constants
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ----------------------------------------------------------------------------
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# ----------------------------------------------------------------------------
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# ----------------------------------------------------------------------------
# --- Development --- #
if DEBUG:
    ALLOWED_HOSTS = []

# --- Production --- #
if not DEBUG:
    ALLOWED_HOSTS = [config('ALLOWED_HOSTS')]

# ----------------------------------------------------------------------------
# SSL and Cookies
# ---- Production ---- #
if not DEBUG:
    ADMINS = [(config('SUPER_USER'), config('EMAIL'))]
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    CSRF_TRUSTED_ORIGINS = [config('TRUSTED_ORIGINS')]

    if DEBUG:
        INTERNAL_IPS = ['127.0.0.1']

# ----------------------------------------------------------------------------
# Application definition

INSTALLED_APPS = [
    # --- Accounts --- #
    'accounts',

    # --- Django Apps --- #
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # --- Django Apps Extras --- #

    # --- My Apps --- #
    'administration',
    'students',
    'base',
    'finance',
    'principal',
    'teachers',
    'parents',
    'secretary',
    'classes',
    'webpage',
]

if DEBUG:
    INSTALLED_APPS.append['debug_toolbar']

# ----------------------------------------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

if DEBUG:
    MIDDLEWARE.append('debug_toolbar.middleware.DebugToolbarMiddleware')

# ----------------------------------------------------------------------------
ROOT_URLCONF = 'schoolManagement.urls'

# ----------------------------------------------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'base.context_global.templates_global_context',
            ],
        },
    },
]

# ----------------------------------------------------------------------------
WSGI_APPLICATION = 'schoolManagement.wsgi.application'

# ----------------------------------------------------------------------------
# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases
# --- Development SQLite3 --- #
# DATABASES = {
#   'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}

# --- Development PostgreSQL --- #
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'data_base_name',
#         'USER': 'data_base_user',
#         'PASSWORD': 'data_base_password',
#         'HOST': 'data_base_host',
#         'PORT': '5432',
#     }
# }

# --- Production --- #
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'data_base_name', 
#         ''USER': 'data_base_user',
#         'PASSWORD': 'data_base_password',
#         'HOST': 'data_base_host',
#         'PORT': '5432',
#     }
# }

# --- PostgreSQL in Heroku --- #
# --- Development --- #

if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('NAME_DB'),
            'USER': config('USER_DB'),
            'PASSWORD': config('PASSWORD_DB'),
            'HOST': config('HOST_DB'),
            'PORT': config('PORT_DB'),
        }
    }

# --- Production --- #
if not DEBUG:
    import dj_database_url

    DATABASES = {
        'default': dj_database_url.config(
            conn_max_age=600,
            ssl_require=True
        )
    }

# ----------------------------------------------------------------------------
# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ----------------------------------------------------------------------------
# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# ----------------------------------------------------------------------------
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = 'media/'

# --- Development --- #
if DEBUG:
    STATIC_ROOT = BASE_DIR / 'staticfiles'
    MEDIA_ROOT = BASE_DIR / 'media'

# --- Production --- #
if not DEBUG:
    STATIC_ROOT = BASE_DIR / 'staticfiles'
    MEDIA_ROOT = BASE_DIR / 'media'

# ----------------------------------------------------------------------------
# --- Email --- #
# --- Development --- #
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# ----------------------------------------------------------------------------
# --- Custom User Model --- #
AUTH_USER_MODEL = 'accounts.CustomUser'

# ----------------------------------------------------------------------------
# --- Login Logout User --- #
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'index_manager'
LOGOUT_REDIRECT_URL = 'index'

# ----------------------------------------------------------------------------
# --- Messages --- #
MESSAGE_TAGS = {
    constants.DEBUG: 'alert_info',
    constants.INFO: 'alert_info',
    constants.SUCCESS: 'alert_success',
    constants.WARNING: 'alert_warning',
    constants.ERROR: 'alert_danger',
}
