'''
Django settings for schoolManagement project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
'''

from pathlib import Path
from django.contrib.messages import constants

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ----------------------------------------------------------------------------
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '************************ secret key ****************************'

# ----------------------------------------------------------------------------
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ----------------------------------------------------------------------------
ALLOWED_HOSTS = []

# ----------------------------------------------------------------------------
# --- Necessary in production for Debug Tolbar --- #
# See INSTALLED_APPS --> Django Apps Extras and MIDDLEWARE
INTERNAL_IPS = ['127.0.0.1']

# ----------------------------------------------------------------------------
# ----- Production ----- #
# SECURE_SSL_REDIRECT = True
# ADMINS = [('domain_name', 'email@domain_name.com')]
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True

# ----------------------------------------------------------------------------
# Application definition

INSTALLED_APPS = [
    # --- Accounts --- #
    'accounts',

    # --- Django Apps --- #
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # --- Django Apps Extras --- #
    'debug_toolbar',

    # --- My Apps --- #
    'administration',
    'students',
    'base',
    'finance',
    'principal',
    'teachers',
    'parents',
    'secretary',
    'classes',
    'webpage',
]

# ----------------------------------------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

# ----------------------------------------------------------------------------
ROOT_URLCONF = 'schoolManagement.urls'

# ----------------------------------------------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ----------------------------------------------------------------------------
WSGI_APPLICATION = 'schoolManagement.wsgi.application'

# ----------------------------------------------------------------------------
# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases
# --- Development SQLite3 --- #
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# --- Development PostgreSQL --- #
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'data_base_name',
#         'USER': 'data_base_user',
#         'PASSWORD': 'data_base_password',
#         'HOST': 'data_base_host',
#         'PORT': '5432',
#     }
# }

# --- Production --- #
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'data_base_name', 
#         ''USER': 'data_base_user',
#         'PASSWORD': 'data_base_password',
#         'HOST': 'data_base_host',
#         'PORT': '5432',
#     }
# }

# ----------------------------------------------------------------------------
# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ----------------------------------------------------------------------------
# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# ----------------------------------------------------------------------------
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

# --- Production --- #
# STATIC_URL = '/static/'
# STATIC_ROOT = '/home/domain_name/www/static'abs

# MEDIA URL = 'media/'
# MEDIA_ROOT = '/home/domain_name/www/media'

# --- Development --- #
STATIC_URL = '/static/'
STATICFILES_ROOT = BASE_DIR / 'static'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ----------------------------------------------------------------------------
# --- Email --- #
# --- Development --- #
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# --- Production --- #
# EMAIL_HOST = 'smtp.domain_name.com'
# EMAIL_HOST_USER = 'email@domain_name.com'
# EMAIL_PORT = 587
# EMAIL_USER_SSL = True
# EMAIL_HOST_PASSWORD = 'email_password'
# DEFAULT_FROM_EMAIL = 'email@domain_name.com'

# ----------------------------------------------------------------------------
# --- Custom User Model --- #
AUTH_USER_MODEL = 'accounts.CustomUser'

# ----------------------------------------------------------------------------
# --- Login Logout User --- #
LOGIN_REDIRECT_URL = 'index'
LOGOUT_REDIRECT_URL = 'index'

# ----------------------------------------------------------------------------
# --- Messages --- #
MESSAGE_TAGS = {
    constants.DEBUG: 'alert-info',
    constants.INFO: 'alert-info',
    constants.SUCCESS: 'alert-success',
    constants.WARNING: 'alert-warning',
    constants.ERROR: 'alert-danger',
}
